import numpy as np
import pandas as pd

def load_half_data():
    df = pd.read_excel('Data/Patient and Treatment Characteristics.xlsx', sheet_name='Filtered')
    LFME = np.array(df['LFME'].tolist())
    RTME = np.array(df['RTME'].tolist())
    new_df = {'SIDE': [], 'GOOD_OR_BAD': [], 'VO': [], 'SA': [], 'SP': [], 'EC': [], 'CO': [], 'MA': [], 'ME': [], 'MI': [], 'ST': [], 'SK': [], 'EN': [], 'UN': [], 'D2': [], 'D10': [], 'D20': [], 'D30': [], 'D40': [], 'D50': [], 'D60': [], 'D70': [], 'D80': [], 'D90': [], 'D98': [], 'V15': [], 'V20': [], 'V25': [], 'V30': [], 'V35': [], 'V40': [], 'V45': []}
    for i in range(0, len(LFME)):
        if LFME[i] < 20 and RTME[i] >= 26:
            new_df['VO'].append(np.array(df['LFVO'].tolist())[i])
            new_df['SA'].append(np.array(df['LFSA'].tolist())[i])
            new_df['SP'].append(np.array(df['LFSP'].tolist())[i])
            new_df['EC'].append(np.array(df['LFEC'].tolist())[i])
            new_df['CO'].append(np.array(df['LFCO'].tolist())[i])
            new_df['MA'].append(np.array(df['LFMA'].tolist())[i])
            new_df['ME'].append(np.array(df['LFME'].tolist())[i])
            new_df['MI'].append(np.array(df['LFMI'].tolist())[i])
            new_df['ST'].append(np.array(df['LFST'].tolist())[i])
            new_df['SK'].append(np.array(df['LFSK'].tolist())[i])
            new_df['EN'].append(np.array(df['LFEN'].tolist())[i])
            new_df['UN'].append(np.array(df['LFUN'].tolist())[i])
            new_df['D2'].append(np.array(df['LFD2'].tolist())[i])
            new_df['D10'].append(np.array(df['LFD10'].tolist())[i])
            new_df['D20'].append(np.array(df['LFD20'].tolist())[i])
            new_df['D30'].append(np.array(df['LFD30'].tolist())[i])
            new_df['D40'].append(np.array(df['LFD40'].tolist())[i])
            new_df['D50'].append(np.array(df['LFD50'].tolist())[i])
            new_df['D60'].append(np.array(df['LFD60'].tolist())[i])
            new_df['D70'].append(np.array(df['LFD70'].tolist())[i])
            new_df['D80'].append(np.array(df['LFD80'].tolist())[i])
            new_df['D90'].append(np.array(df['LFD90'].tolist())[i])
            new_df['D98'].append(np.array(df['LFD98'].tolist())[i])
            new_df['V15'].append(np.array(df['LFV15'].tolist())[i])
            new_df['V20'].append(np.array(df['LFV20'].tolist())[i])
            new_df['V25'].append(np.array(df['LFV25'].tolist())[i])
            new_df['V30'].append(np.array(df['LFV30'].tolist())[i])
            new_df['V35'].append(np.array(df['LFV35'].tolist())[i])
            new_df['V40'].append(np.array(df['LFV40'].tolist())[i])
            new_df['V45'].append(np.array(df['LFV45'].tolist())[i])
            new_df['SIDE'].append('left')
            new_df['GOOD_OR_BAD'].append('good')
        elif LFME[i] >= 26 and RTME[i] < 20:
            new_df['VO'].append(np.array(df['RTVO'].tolist())[i])
            new_df['SA'].append(np.array(df['RTSA'].tolist())[i])
            new_df['SP'].append(np.array(df['RTSP'].tolist())[i])
            new_df['EC'].append(np.array(df['RTEC'].tolist())[i])
            new_df['CO'].append(np.array(df['RTCO'].tolist())[i])
            new_df['MA'].append(np.array(df['RTMA'].tolist())[i])
            new_df['ME'].append(np.array(df['RTME'].tolist())[i])
            new_df['MI'].append(np.array(df['RTMI'].tolist())[i])
            new_df['ST'].append(np.array(df['RTST'].tolist())[i])
            new_df['SK'].append(np.array(df['RTSK'].tolist())[i])
            new_df['EN'].append(np.array(df['RTEN'].tolist())[i])
            new_df['UN'].append(np.array(df['RTUN'].tolist())[i])
            new_df['D2'].append(np.array(df['RTD2'].tolist())[i])
            new_df['D10'].append(np.array(df['RTD10'].tolist())[i])
            new_df['D20'].append(np.array(df['RTD20'].tolist())[i])
            new_df['D30'].append(np.array(df['RTD30'].tolist())[i])
            new_df['D40'].append(np.array(df['RTD40'].tolist())[i])
            new_df['D50'].append(np.array(df['RTD50'].tolist())[i])
            new_df['D60'].append(np.array(df['RTD60'].tolist())[i])
            new_df['D70'].append(np.array(df['RTD70'].tolist())[i])
            new_df['D80'].append(np.array(df['RTD80'].tolist())[i])
            new_df['D90'].append(np.array(df['RTD90'].tolist())[i])
            new_df['D98'].append(np.array(df['RTD98'].tolist())[i])
            new_df['V15'].append(np.array(df['RTV15'].tolist())[i])
            new_df['V20'].append(np.array(df['RTV20'].tolist())[i])
            new_df['V25'].append(np.array(df['RTV25'].tolist())[i])
            new_df['V30'].append(np.array(df['RTV30'].tolist())[i])
            new_df['V35'].append(np.array(df['RTV35'].tolist())[i])
            new_df['V40'].append(np.array(df['RTV40'].tolist())[i])
            new_df['V45'].append(np.array(df['RTV45'].tolist())[i])
            new_df['SIDE'].append('right')
            new_df['GOOD_OR_BAD'].append('good')
        elif LFME[i] >= 26 and RTME[i] >= 26:
            new_df['VO'].append(np.mean([np.array(df['RTVO'].tolist())[i], np.array(df['LFVO'].tolist())[i]], axis=0))
            new_df['SA'].append(np.mean([np.array(df['RTSA'].tolist())[i], np.array(df['LFSA'].tolist())[i]], axis=0))
            new_df['SP'].append(np.mean([np.array(df['RTSP'].tolist())[i], np.array(df['LFSP'].tolist())[i]], axis=0))
            new_df['EC'].append(np.mean([np.array(df['RTEC'].tolist())[i], np.array(df['LFEC'].tolist())[i]], axis=0))
            new_df['CO'].append(np.mean([np.array(df['RTCO'].tolist())[i], np.array(df['LFCO'].tolist())[i]], axis=0))
            new_df['MA'].append(np.mean([np.array(df['RTMA'].tolist())[i], np.array(df['LFMA'].tolist())[i]], axis=0))
            new_df['ME'].append(np.mean([np.array(df['RTME'].tolist())[i], np.array(df['LFME'].tolist())[i]], axis=0))
            new_df['MI'].append(np.mean([np.array(df['RTMI'].tolist())[i], np.array(df['LFMI'].tolist())[i]], axis=0))
            new_df['ST'].append(np.mean([np.array(df['RTST'].tolist())[i], np.array(df['LFST'].tolist())[i]], axis=0))
            new_df['SK'].append(np.mean([np.array(df['RTSK'].tolist())[i], np.array(df['LFSK'].tolist())[i]], axis=0))
            new_df['EN'].append(np.mean([np.array(df['RTEN'].tolist())[i], np.array(df['LFEN'].tolist())[i]], axis=0))
            new_df['UN'].append(np.mean([np.array(df['RTUN'].tolist())[i], np.array(df['LFUN'].tolist())[i]], axis=0))
            new_df['D2'].append(np.mean([np.array(df['RTD2'].tolist())[i], np.array(df['LFD2'].tolist())[i]], axis=0))
            new_df['D10'].append(np.mean([np.array(df['RTD10'].tolist())[i], np.array(df['LFD10'].tolist())[i]], axis=0))
            new_df['D20'].append(np.mean([np.array(df['RTD20'].tolist())[i], np.array(df['LFD20'].tolist())[i]], axis=0))
            new_df['D30'].append(np.mean([np.array(df['RTD30'].tolist())[i], np.array(df['LFD30'].tolist())[i]], axis=0))
            new_df['D40'].append(np.mean([np.array(df['RTD40'].tolist())[i], np.array(df['LFD40'].tolist())[i]], axis=0))
            new_df['D50'].append(np.mean([np.array(df['RTD50'].tolist())[i], np.array(df['LFD50'].tolist())[i]], axis=0))
            new_df['D60'].append(np.mean([np.array(df['RTD60'].tolist())[i], np.array(df['LFD60'].tolist())[i]], axis=0))
            new_df['D70'].append(np.mean([np.array(df['RTD70'].tolist())[i], np.array(df['LFD70'].tolist())[i]], axis=0))
            new_df['D80'].append(np.mean([np.array(df['RTD80'].tolist())[i], np.array(df['LFD80'].tolist())[i]], axis=0))
            new_df['D90'].append(np.mean([np.array(df['RTD90'].tolist())[i], np.array(df['LFD90'].tolist())[i]], axis=0))
            new_df['D98'].append(np.mean([np.array(df['RTD98'].tolist())[i], np.array(df['LFD98'].tolist())[i]], axis=0))
            new_df['V15'].append(np.mean([np.array(df['RTV15'].tolist())[i], np.array(df['LFV15'].tolist())[i]], axis=0))
            new_df['V20'].append(np.mean([np.array(df['RTV20'].tolist())[i], np.array(df['LFV20'].tolist())[i]], axis=0))
            new_df['V25'].append(np.mean([np.array(df['RTV25'].tolist())[i], np.array(df['LFV25'].tolist())[i]], axis=0))
            new_df['V30'].append(np.mean([np.array(df['RTV30'].tolist())[i], np.array(df['LFV30'].tolist())[i]], axis=0))
            new_df['V35'].append(np.mean([np.array(df['RTV35'].tolist())[i], np.array(df['LFV35'].tolist())[i]], axis=0))
            new_df['V40'].append(np.mean([np.array(df['RTV40'].tolist())[i], np.array(df['LFV40'].tolist())[i]], axis=0))
            new_df['V45'].append(np.mean([np.array(df['RTV45'].tolist())[i], np.array(df['LFV45'].tolist())[i]], axis=0))
            new_df['SIDE'].append('mean')
            new_df['GOOD_OR_BAD'].append('bad')
        elif LFME[i] < 26 and RTME[i] < 26:
            new_df['VO'].append(np.mean([np.array(df['RTVO'].tolist())[i], np.array(df['LFVO'].tolist())[i]], axis=0))
            new_df['SA'].append(np.mean([np.array(df['RTSA'].tolist())[i], np.array(df['LFSA'].tolist())[i]], axis=0))
            new_df['SP'].append(np.mean([np.array(df['RTSP'].tolist())[i], np.array(df['LFSP'].tolist())[i]], axis=0))
            new_df['EC'].append(np.mean([np.array(df['RTEC'].tolist())[i], np.array(df['LFEC'].tolist())[i]], axis=0))
            new_df['CO'].append(np.mean([np.array(df['RTCO'].tolist())[i], np.array(df['LFCO'].tolist())[i]], axis=0))
            new_df['MA'].append(np.mean([np.array(df['RTMA'].tolist())[i], np.array(df['LFMA'].tolist())[i]], axis=0))
            new_df['ME'].append(np.mean([np.array(df['RTME'].tolist())[i], np.array(df['LFME'].tolist())[i]], axis=0))
            new_df['MI'].append(np.mean([np.array(df['RTMI'].tolist())[i], np.array(df['LFMI'].tolist())[i]], axis=0))
            new_df['ST'].append(np.mean([np.array(df['RTST'].tolist())[i], np.array(df['LFST'].tolist())[i]], axis=0))
            new_df['SK'].append(np.mean([np.array(df['RTSK'].tolist())[i], np.array(df['LFSK'].tolist())[i]], axis=0))
            new_df['EN'].append(np.mean([np.array(df['RTEN'].tolist())[i], np.array(df['LFEN'].tolist())[i]], axis=0))
            new_df['UN'].append(np.mean([np.array(df['RTUN'].tolist())[i], np.array(df['LFUN'].tolist())[i]], axis=0))
            new_df['D2'].append(np.mean([np.array(df['RTD2'].tolist())[i], np.array(df['LFD2'].tolist())[i]], axis=0))
            new_df['D10'].append(np.mean([np.array(df['RTD10'].tolist())[i], np.array(df['LFD10'].tolist())[i]], axis=0))
            new_df['D20'].append(np.mean([np.array(df['RTD20'].tolist())[i], np.array(df['LFD20'].tolist())[i]], axis=0))
            new_df['D30'].append(np.mean([np.array(df['RTD30'].tolist())[i], np.array(df['LFD30'].tolist())[i]], axis=0))
            new_df['D40'].append(np.mean([np.array(df['RTD40'].tolist())[i], np.array(df['LFD40'].tolist())[i]], axis=0))
            new_df['D50'].append(np.mean([np.array(df['RTD50'].tolist())[i], np.array(df['LFD50'].tolist())[i]], axis=0))
            new_df['D60'].append(np.mean([np.array(df['RTD60'].tolist())[i], np.array(df['LFD60'].tolist())[i]], axis=0))
            new_df['D70'].append(np.mean([np.array(df['RTD70'].tolist())[i], np.array(df['LFD70'].tolist())[i]], axis=0))
            new_df['D80'].append(np.mean([np.array(df['RTD80'].tolist())[i], np.array(df['LFD80'].tolist())[i]], axis=0))
            new_df['D90'].append(np.mean([np.array(df['RTD90'].tolist())[i], np.array(df['LFD90'].tolist())[i]], axis=0))
            new_df['D98'].append(np.mean([np.array(df['RTD98'].tolist())[i], np.array(df['LFD98'].tolist())[i]], axis=0))
            new_df['V15'].append(np.mean([np.array(df['RTV15'].tolist())[i], np.array(df['LFV15'].tolist())[i]], axis=0))
            new_df['V20'].append(np.mean([np.array(df['RTV20'].tolist())[i], np.array(df['LFV20'].tolist())[i]], axis=0))
            new_df['V25'].append(np.mean([np.array(df['RTV25'].tolist())[i], np.array(df['LFV25'].tolist())[i]], axis=0))
            new_df['V30'].append(np.mean([np.array(df['RTV30'].tolist())[i], np.array(df['LFV30'].tolist())[i]], axis=0))
            new_df['V35'].append(np.mean([np.array(df['RTV35'].tolist())[i], np.array(df['LFV35'].tolist())[i]], axis=0))
            new_df['V40'].append(np.mean([np.array(df['RTV40'].tolist())[i], np.array(df['LFV40'].tolist())[i]], axis=0))
            new_df['V45'].append(np.mean([np.array(df['RTV45'].tolist())[i], np.array(df['LFV45'].tolist())[i]], axis=0))
            new_df['SIDE'].append('mean')
            new_df['GOOD_OR_BAD'].append('good')
        else:
            if abs(LFME[i] - RTME[i]) <= 10:
                new_df['VO'].append(
                    np.mean([np.array(df['RTVO'].tolist())[i], np.array(df['LFVO'].tolist())[i]], axis=0))
                new_df['SA'].append(
                    np.mean([np.array(df['RTSA'].tolist())[i], np.array(df['LFSA'].tolist())[i]], axis=0))
                new_df['SP'].append(
                    np.mean([np.array(df['RTSP'].tolist())[i], np.array(df['LFSP'].tolist())[i]], axis=0))
                new_df['EC'].append(
                    np.mean([np.array(df['RTEC'].tolist())[i], np.array(df['LFEC'].tolist())[i]], axis=0))
                new_df['CO'].append(
                    np.mean([np.array(df['RTCO'].tolist())[i], np.array(df['LFCO'].tolist())[i]], axis=0))
                new_df['MA'].append(
                    np.mean([np.array(df['RTMA'].tolist())[i], np.array(df['LFMA'].tolist())[i]], axis=0))
                new_df['ME'].append(
                    np.mean([np.array(df['RTME'].tolist())[i], np.array(df['LFME'].tolist())[i]], axis=0))
                new_df['MI'].append(
                    np.mean([np.array(df['RTMI'].tolist())[i], np.array(df['LFMI'].tolist())[i]], axis=0))
                new_df['ST'].append(
                    np.mean([np.array(df['RTST'].tolist())[i], np.array(df['LFST'].tolist())[i]], axis=0))
                new_df['SK'].append(
                    np.mean([np.array(df['RTSK'].tolist())[i], np.array(df['LFSK'].tolist())[i]], axis=0))
                new_df['EN'].append(
                    np.mean([np.array(df['RTEN'].tolist())[i], np.array(df['LFEN'].tolist())[i]], axis=0))
                new_df['UN'].append(
                    np.mean([np.array(df['RTUN'].tolist())[i], np.array(df['LFUN'].tolist())[i]], axis=0))
                new_df['D2'].append(
                    np.mean([np.array(df['RTD2'].tolist())[i], np.array(df['LFD2'].tolist())[i]], axis=0))
                new_df['D10'].append(
                    np.mean([np.array(df['RTD10'].tolist())[i], np.array(df['LFD10'].tolist())[i]], axis=0))
                new_df['D20'].append(
                    np.mean([np.array(df['RTD20'].tolist())[i], np.array(df['LFD20'].tolist())[i]], axis=0))
                new_df['D30'].append(
                    np.mean([np.array(df['RTD30'].tolist())[i], np.array(df['LFD30'].tolist())[i]], axis=0))
                new_df['D40'].append(
                    np.mean([np.array(df['RTD40'].tolist())[i], np.array(df['LFD40'].tolist())[i]], axis=0))
                new_df['D50'].append(
                    np.mean([np.array(df['RTD50'].tolist())[i], np.array(df['LFD50'].tolist())[i]], axis=0))
                new_df['D60'].append(
                    np.mean([np.array(df['RTD60'].tolist())[i], np.array(df['LFD60'].tolist())[i]], axis=0))
                new_df['D70'].append(
                    np.mean([np.array(df['RTD70'].tolist())[i], np.array(df['LFD70'].tolist())[i]], axis=0))
                new_df['D80'].append(
                    np.mean([np.array(df['RTD80'].tolist())[i], np.array(df['LFD80'].tolist())[i]], axis=0))
                new_df['D90'].append(
                    np.mean([np.array(df['RTD90'].tolist())[i], np.array(df['LFD90'].tolist())[i]], axis=0))
                new_df['D98'].append(
                    np.mean([np.array(df['RTD98'].tolist())[i], np.array(df['LFD98'].tolist())[i]], axis=0))
                new_df['V15'].append(
                    np.mean([np.array(df['RTV15'].tolist())[i], np.array(df['LFV15'].tolist())[i]], axis=0))
                new_df['V20'].append(
                    np.mean([np.array(df['RTV20'].tolist())[i], np.array(df['LFV20'].tolist())[i]], axis=0))
                new_df['V25'].append(
                    np.mean([np.array(df['RTV25'].tolist())[i], np.array(df['LFV25'].tolist())[i]], axis=0))
                new_df['V30'].append(
                    np.mean([np.array(df['RTV30'].tolist())[i], np.array(df['LFV30'].tolist())[i]], axis=0))
                new_df['V35'].append(
                    np.mean([np.array(df['RTV35'].tolist())[i], np.array(df['LFV35'].tolist())[i]], axis=0))
                new_df['V40'].append(
                    np.mean([np.array(df['RTV40'].tolist())[i], np.array(df['LFV40'].tolist())[i]], axis=0))
                new_df['V45'].append(
                    np.mean([np.array(df['RTV45'].tolist())[i], np.array(df['LFV45'].tolist())[i]], axis=0))
                new_df['SIDE'].append('mean')
                new_df['GOOD_OR_BAD'].append('okay')
            elif LFME[i] > RTME[i]:
                new_df['VO'].append(np.array(df['RTVO'].tolist())[i])
                new_df['SA'].append(np.array(df['RTSA'].tolist())[i])
                new_df['SP'].append(np.array(df['RTSP'].tolist())[i])
                new_df['EC'].append(np.array(df['RTEC'].tolist())[i])
                new_df['CO'].append(np.array(df['RTCO'].tolist())[i])
                new_df['MA'].append(np.array(df['RTMA'].tolist())[i])
                new_df['ME'].append(np.array(df['RTME'].tolist())[i])
                new_df['MI'].append(np.array(df['RTMI'].tolist())[i])
                new_df['ST'].append(np.array(df['RTST'].tolist())[i])
                new_df['SK'].append(np.array(df['RTSK'].tolist())[i])
                new_df['EN'].append(np.array(df['RTEN'].tolist())[i])
                new_df['UN'].append(np.array(df['RTUN'].tolist())[i])
                new_df['D2'].append(np.array(df['RTD2'].tolist())[i])
                new_df['D10'].append(np.array(df['RTD10'].tolist())[i])
                new_df['D20'].append(np.array(df['RTD20'].tolist())[i])
                new_df['D30'].append(np.array(df['RTD30'].tolist())[i])
                new_df['D40'].append(np.array(df['RTD40'].tolist())[i])
                new_df['D50'].append(np.array(df['RTD50'].tolist())[i])
                new_df['D60'].append(np.array(df['RTD60'].tolist())[i])
                new_df['D70'].append(np.array(df['RTD70'].tolist())[i])
                new_df['D80'].append(np.array(df['RTD80'].tolist())[i])
                new_df['D90'].append(np.array(df['RTD90'].tolist())[i])
                new_df['D98'].append(np.array(df['RTD98'].tolist())[i])
                new_df['V15'].append(np.array(df['RTV15'].tolist())[i])
                new_df['V20'].append(np.array(df['RTV20'].tolist())[i])
                new_df['V25'].append(np.array(df['RTV25'].tolist())[i])
                new_df['V30'].append(np.array(df['RTV30'].tolist())[i])
                new_df['V35'].append(np.array(df['RTV35'].tolist())[i])
                new_df['V40'].append(np.array(df['RTV40'].tolist())[i])
                new_df['V45'].append(np.array(df['RTV45'].tolist())[i])
                new_df['SIDE'].append('right')
                new_df['GOOD_OR_BAD'].append('bad')
            elif LFME[i] < RTME[i]:
                new_df['VO'].append(np.array(df['LFVO'].tolist())[i])
                new_df['SA'].append(np.array(df['LFSA'].tolist())[i])
                new_df['SP'].append(np.array(df['LFSP'].tolist())[i])
                new_df['EC'].append(np.array(df['LFEC'].tolist())[i])
                new_df['CO'].append(np.array(df['LFCO'].tolist())[i])
                new_df['MA'].append(np.array(df['LFMA'].tolist())[i])
                new_df['ME'].append(np.array(df['LFME'].tolist())[i])
                new_df['MI'].append(np.array(df['LFMI'].tolist())[i])
                new_df['ST'].append(np.array(df['LFST'].tolist())[i])
                new_df['SK'].append(np.array(df['LFSK'].tolist())[i])
                new_df['EN'].append(np.array(df['LFEN'].tolist())[i])
                new_df['UN'].append(np.array(df['LFUN'].tolist())[i])
                new_df['D2'].append(np.array(df['LFD2'].tolist())[i])
                new_df['D10'].append(np.array(df['LFD10'].tolist())[i])
                new_df['D20'].append(np.array(df['LFD20'].tolist())[i])
                new_df['D30'].append(np.array(df['LFD30'].tolist())[i])
                new_df['D40'].append(np.array(df['LFD40'].tolist())[i])
                new_df['D50'].append(np.array(df['LFD50'].tolist())[i])
                new_df['D60'].append(np.array(df['LFD60'].tolist())[i])
                new_df['D70'].append(np.array(df['LFD70'].tolist())[i])
                new_df['D80'].append(np.array(df['LFD80'].tolist())[i])
                new_df['D90'].append(np.array(df['LFD90'].tolist())[i])
                new_df['D98'].append(np.array(df['LFD98'].tolist())[i])
                new_df['V15'].append(np.array(df['LFV15'].tolist())[i])
                new_df['V20'].append(np.array(df['LFV20'].tolist())[i])
                new_df['V25'].append(np.array(df['LFV25'].tolist())[i])
                new_df['V30'].append(np.array(df['LFV30'].tolist())[i])
                new_df['V35'].append(np.array(df['LFV35'].tolist())[i])
                new_df['V40'].append(np.array(df['LFV40'].tolist())[i])
                new_df['V45'].append(np.array(df['LFV45'].tolist())[i])
                new_df['SIDE'].append('left')
                new_df['GOOD_OR_BAD'].append('bad')

    with pd.ExcelWriter('Data/Patient and Treatment Characteristics.xlsx', mode='a') as writer:
        new_df = pd.DataFrame(data=new_df)
        new_df.to_excel(writer, sheet_name='AveragedFiltered')


if __name__ == '__main__':
    load_half_data()